In [10]:
import jqdatasdk
from jqdatasdk import finance

In [11]:
jqdatasdk.auth('13811815618','Shuzi307104!')

In [18]:
# 获取几只股票的资金流向
df=jqdatasdk.get_money_flow(['000001.XSHE', '000040.XSHE', '000099.XSHE'], 
                  '2022-01-01', '2022-01-30', ['date','sec_code',
                                               'change_pct','net_amount_main',
                                               'net_pct_main','net_amount_xl',
                                               'net_pct_xl','net_amount_l','net_pct_l',
                                            'net_amount_m','net_pct_m','net_amount_s','net_pct_s'])

In [19]:
df[:4]

,date,sec_code,change_pct,net_amount_main,net_pct_main,net_amount_xl,net_pct_xl,net_amount_l,net_pct_l,net_amount_m,net_pct_m,net_amount_s,net_pct_s
0,2022-01-04,000099.XSHE,2.66,791.1952,5.1402,888.4319,5.7719,-97.2367,-0.6317,-625.1305,-4.0613,-166.0648,-1.0789
1,2022-01-04,000001.XSHE,1.09,-9326.0000,-4.8601,-5155.0864,-2.6865,-4170.9136,-2.1736,2393.7120,1.2474,6932.2880,3.6127
2,2022-01-04,000040.XSHE,0.26,191.5728,1.2289,408.7461,2.6220,-217.1733,-1.3931,-580.5310,-3.7239,388.9582,2.4951
3,2022-01-05,000040.XSHE,-1.28,-603.6616,-4.9186,-51.0253,-0.4158,-552.6363,-4.5029,-109.7795,-0.8945,713.4412,5.8131